### ISSUE TITLE
how to install pyls

### ISSUE THREAD

**Issue by QuantamLevel** [atom-community/ide-python#163]
![Screenshot (2)](https://user-images.githubusercontent.com/47340964/54537096-e1164580-49cc-11e9-8d0b-6ace30351f81.png)

**Comment by cscomic** [comment]
same problem on windows pc. pyls can be run in command line

**Comment by Yash10bloodstorm** [comment]
i have the same issue on macOS Mojave 
I tried a few different things doesn't work at all.
HELP!!!

**Comment by SKalt** [comment]
When I've encountered this error message in the past, I had started `atom` within a process using a python environment which didn't have access to `pyls`.

To debug, interpret the messages from the following checks of your python environment
```sh
# within the directory where you want to start pyls 
python --version
python -c 'import sys; print("\n".join(sys.path))'
python -c 'import 
```
When reporting a bug in any atom package, always include the console log information (ctrl+shift+i on linux/ms or cmd+opt+i on mac).  I expect the error message from ide-python trying to boot the server would appear.
