### ISSUE TITLE
How to compile? 

### ISSUE THREAD

**Issue by TiansuYu** [atom-community/ide-python#169]
I know this may sound like a naive question, I've followed the instruction to installed everything there, and you could find the package saids installed on atom. But where is the compile botton? Or the keybinding? 

I tried to look it up everywhere in atom, but nothing to be found. 

<img width="451" alt="Screenshot 2019-05-05 at 14 37 16" src="https://user-images.githubusercontent.com/9974655/57194140-93857600-6f43-11e9-94e6-38e9af3e44c1.png">

<img width="691" alt="Screenshot 2019-05-05 at 14 42 08" src="https://user-images.githubusercontent.com/9974655/57194179-05f65600-6f44-11e9-8bc3-f9f076d16c1b.png">

**Comment by exploide** [comment]
What do you want to compile? Python is usually interpreted. You do not build a Python package within Atom. You write the code and then execute it on command line.

If you intend to trigger the execution of your Python script within Atom, there are numerous packages available at https://atom.io/packages. But I don't see any benefit from doing this. I just use my command line.

**Comment by Miraclei** [comment]
Too much spoiled with mathematica, i guess, thats the reason, everything in atom,  i want to build a key binding with enter+shift

Good to know, thx
