### ISSUE TITLE
Unable to start the Python language server problem

### ISSUE THREAD

**Issue by AlexKHPark** [atom-community/ide-python#182]
it keeps coming up.
I have tried installing it several times, but still not working..
![스크린샷 2019-10-17 오후 2 19 44](https://user-images.githubusercontent.com/42567860/66979678-5ffd6900-f0e9-11e9-9e65-5ee4d384c71f.png)
Mac OSX Catalina

**Comment by figa17** [comment]
I have the same issue in mi pc.
I use debian 10 and conda whith python 3.6

**Comment by mjrodgers** [comment]
I'm also having this come up for the past week or so. macOS Mojave (10.14.6), Atom 1.40.1, conda with python 3.6.9, pyls 0.29.1 installed.

**Comment by leotada** [comment]
Same here, on Fedora.

**Comment by arnoldse** [comment]
Same here, on MacOS Catalina & pyenv

**Comment by peterVG** [comment]
My Macbook Catalina OS came with Python 2.7 pre-installed. I used Homebrew to install Python 3.7 and I ran into this issue after I installed Atom.io with the ide-python package. 
I tried arnoldse's fix ^ above by pointing to Python3's pyenv absolute path but that didn't work.
However, when I just changed the Python Executable setting from the default 'pyton' to 'python3' it worked. I no longer get the Python language server error on startup and have ide-python support.

**Comment by nwzy** [comment]
> Same here, on MacOS Catalina, python 3.8.1 & pyenv
> 
> *** update ***
> works for me, if I change the default path to the absolute path to the pyenv path
> <img alt="Screenshot 2020-03-06 at 17 11 14" width="993" src="https://user-images.githubusercontent.com/16198508/76100916-d255e380-5fcd-11ea-8e46-6f48751ae791.png">

This worked for me

**Comment by yuvraj2112** [comment]
It worked for me by changing the default value from 'python' to 'python3'

![image](https://user-images.githubusercontent.com/11533989/78998773-eeb5e480-7b66-11ea-836b-da8aea9d0c3f.png)

**Comment by AntoineZappa** [comment]
> It worked for me by changing the default value from 'python' to 'python3'
> 
> ![image](https://user-images.githubusercontent.com/11533989/78998773-eeb5e480-7b66-11ea-836b-da8aea9d0c3f.png)

Nice!

**Comment by hugoby42** [comment]
> > It worked for me by changing the default value from 'python' to 'python3'
> > ![image](https://user-images.githubusercontent.com/11533989/78998773-eeb5e480-7b66-11ea-836b-da8aea9d0c3f.png)
> 
> Nice!



> It worked for me by changing the default value from 'python' to 'python3'
> 
> ![image](https://user-images.githubusercontent.com/11533989/78998773-eeb5e480-7b66-11ea-836b-da8aea9d0c3f.png)

Same for me !

**Comment by ravikumar1995** [comment]
i have same problem, i changed python to python3 still it showing error

**Comment by gustheitguru** [comment]
I am still having the same error as well. I have updated all of my start points to use python3


this is what happens in terminal when i hit F5 or F6

```
Last login: Sun Aug  2 13:44:22 on ttys001
MacBook@MacBook-Pro ~ %  python /Users/MacBook/.atom/packages/atom-python-run/lib/../cp/main.py --pause -- python3 /Users/MacBook/Documents/GitHub/Python Practice/string.py


/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: can't open file '/Users/MacBook/Documents/GitHub/Python': [Errno 2] No such file or directory

Process returned 2 (0x2)	execution time : 0.039 s
Close this window to continue...
MacBook@MacBook-Pro ~ % 
```

**Comment by victor4pro** [comment]
I just write "python3" in the Python Executable field and everything woroked for me

**Comment by saanpritom** [comment]
I have faced the same issue on my Mac. I have tried the solution mentioned above. Both changing the python executable to the virtualenv python path and the default python3 path but the problem not solved. Then on my virtualenv I have uninstalled both python-language-server[all] and pyls. After uninstalling I have installed only python-language-server[all] using pip on my virtualenv. But I didn't install pyls. And the problem is solved. I think the python language server ships with a pyls on it and which is different than the independent pyls library and Atom can't determine which pyls to take.

**Comment by aminya** [comment]
Is there a generic fix that I can add to the package? Is anyone interested in making a PR?

**Comment by erickfis** [comment]
> > > It worked for me by changing the default value from 'python' to 'python3'
> > > ![image](https://user-images.githubusercontent.com/11533989/78998773-eeb5e480-7b66-11ea-836b-da8aea9d0c3f.png)
> > 
> > 
> > Nice!
> 
> > It worked for me by changing the default value from 'python' to 'python3'
> > ![image](https://user-images.githubusercontent.com/11533989/78998773-eeb5e480-7b66-11ea-836b-da8aea9d0c3f.png)
> 
> Same for me !

Worked for me!

**Comment by Chris-Rasburn** [comment]
I'm getting the following error message:

>Unable to start the Python language server.
>
>Make sure to install pylsp 0.19 or newer by running:
>
>python -m pip install 'python-lsp-server[all]'
>python -m pip install git+https://github.com/tomv564/pyls-mypy.git

I'm new to all this, so probably did something wrong. 

I'm using:  
- WSL2,  
- Debian 1.12.1.0,  
- Atom 1.58.0.  
- I have Python 2.7.18 and Python 3.9.2 installed.   
- ide-python 1.9.7

python3 -m pyls --help       returns:

>usage: __main__.py [-h] [--tcp] [--host HOST] [--port PORT] [--check-parent-process] [--log-config LOG_CONFIG | --log-file LOG_FILE] [-v]
>
>Python Language Server

python -m pyls --help       returns:

>/usr/bin/python: No module named pyls

I'm sure there is a simple answer to this, but I'm baffled.  Apologies if this isn't the right place to ask this question - point me to the right place.
