### ISSUE TITLE
The 'Ignore' setting for flake8 doesn't work

### ISSUE THREAD

**Issue by matthewgdv** [atom-community/ide-python#185]
Reproducing it is as easy as the following:

````
(
    1
    + 1  # line break before binary operator
)
````

Given the default settings (where W503 is ignored), this error should be suppressed, but it gets through. Likewise, all other errors that you add on to the ignore setting still get through.

**Comment by goi42** [comment]
I am not able to reproduce this with the latest version.

**Comment by matthewgdv** [comment]
You're right, it seems to be working now. Happy to close this issue.
