### ISSUE TITLE
"goto definition" does not work

### ISSUE THREAD

**Issue by vfilimonov** [atom-community/ide-python#230]
Goto definition functionality does not work with `ide-python`:

1 `Go to Declaration` menu item does not do anything
2 [goto-definition](https://atom.io/packages/goto-definition) package:
  - jumps to the beginning of the file if the function defined in the same file. 
  - If function is defined in another module and imported as "from module import function" - it jumps to the beginning of the respective module
  - if function is called via module name (`import module` ... `module.function()`): it could jump to the declaration if there are no functions with similar names are defined in the whole atom project. If such functions are found (even if they are in another library which is not imported) - it will suggest to choose.

Versions:
- ide-python 1.6.2
- python-language-server 0.36.1
- jedi 0.17.2
- goto-definition 1.3.4

**Comment by ThatXliner** [comment]
It works for me. Did you install [the goto-definition from atom-community](https://github.com/atom-community/atom-ide-definitions)?
