### ISSUE TITLE
Failed to activate the ide-python package

### ISSUE THREAD

**Issue by terranandes** [atom-community/ide-python#242]
Due to files missing:
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 
'C:\\Users\\XXXXXABC\\
AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\jedi\\third_party\\django-stubs\\django-stubs\\contrib\\contenttypes\\management\\commands\\remove_stale_contenttypes.pyi'
When running 'python -m pip install 'python-language-server[all]'

**Comment by aminya** [comment]
This is not related to this package.

Run the following command again:
```
python -m pip install 'python-language-server[all]
```
