### ISSUE TITLE
Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?inva...

### ISSUE THREAD

**Issue by AlanAguilarSologuren** [atom-community/ide-python#278]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Ubuntu 20.04.2
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.3

### Stack Trace

Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130

**Comment by aminya** [comment]
This is a connection issue. Please re-download
```
apm uninstall ide-python
apm install ide-python
```
