### ISSUE TITLE
Hello, could you please give me some explanation about why I cannot install script?

### ISSUE THREAD

**Issue by boseongyun** [atom-community/ide-python#280]
<img width="776" alt="install fail" src="https://user-images.githubusercontent.com/56447992/108418175-827c2680-71f6-11eb-8030-48e6cd90712e.png">

**Comment by boseongyun** [comment]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/private/var/folders/rp/24bnh2750wl6z_c3lr81gszh0000gn/T/AppTranslocation/BBD2C53F-A7A3-4BB8-AE91-E1BFF9A9BBB6/d/Atom ' +
1 verbose cli     '2.app/Contents/Resources/app/apm/bin/node',
1 verbose cli   '/private/var/folders/rp/24bnh2750wl6z_c3lr81gszh0000gn/T/AppTranslocation/BBD2C53F-A7A3-4BB8-AE91-E1BFF9A9BBB6/d/Atom ' +
1 verbose cli     '2.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   '/Users/boseongyun/.atom/.apm/.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   '/Users/boseongyun/.atom/.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/script/versions/3.29.3/tarball',
1 verbose cli   '--target=6.1.12',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.4.0
4 verbose npm-session edf2314457fa6235
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/atom-community/atom-script/legacy.tar.gz/v3.29.3 1504ms (from cache)
8 silly pacote remote manifest for undefined@https://www.atom.io/api/packages/script/versions/3.29.3/tarball fetched in 1548ms
9 timing stage:loadCurrentTree Completed in 1564ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule script@3.29.3 checking installable status
17 http fetch GET 304 https://registry.npmjs.org/ansi-to-html 178ms (from cache)
18 http fetch GET 304 https://registry.npmjs.org/underscore 177ms (from cache)
19 silly pacote range manifest for ansi-to-html@^0.6.14 fetched in 184ms
20 silly resolveWithNewModule ansi-to-html@0.6.14 checking installable status
21 http fetch GET 304 https://registry.npmjs.org/atom-message-panel 186ms (from cache)
22 http fetch GET 304 https://registry.npmjs.org/atom-space-pen-views-plus 184ms (from cache)
23 silly pacote range manifest for underscore@^1.12.0 fetched in 185ms
24 silly resolveWithNewModule underscore@1.12.0 checking installable status
25 http fetch GET 304 https://registry.npmjs.org/@babel%2fpreset-react 194ms (from cache)
26 http fetch GET 304 https://registry.npmjs.org/uuid 188ms (from cache)
27 silly pacote version manifest for atom-message-panel@1.3.1 fetched in 197ms
28 silly resolveWithNewModule atom-message-panel@1.3.1 checking installable status
29 http fetch GET 304 https://registry.npmjs.org/strip-ansi 194ms (from cache)
30 http fetch GET 304 https://registry.npmjs.org/@babel%2fcli 203ms (from cache)
31 silly pacote range manifest for atom-space-pen-views-plus@^3.0.4 fetched in 198ms
32 silly resolveWithNewModule atom-space-pen-views-plus@3.0.4 checking installable status
33 silly pacote range manifest for @babel/preset-react@^7.12.10 fetched in 205ms
34 silly resolveWithNewModule @babel/preset-react@7.12.13 checking installable status
35 silly pacote range manifest for uuid@^8.3.2 fetched in 197ms
36 silly resolveWithNewModule uuid@8.3.2 checking installable status
37 http fetch GET 304 https://registry.npmjs.org/@babel%2fcore 208ms (from cache)
38 silly pacote range manifest for strip-ansi@^6.0.0 fetched in 203ms
39 silly resolveWithNewModule strip-ansi@6.0.0 checking installable status
40 silly pacote range manifest for @babel/cli@^7.12.10 fetched in 216ms
41 silly resolveWithNewModule @babel/cli@7.12.17 checking installable status
42 silly pacote range manifest for @babel/core@^7.12.10 fetched in 215ms
43 silly resolveWithNewModule @babel/core@7.12.17 checking installable status
44 http fetch GET 304 https://registry.npmjs.org/@babel%2fpreset-env 215ms (from cache)
45 silly fetchPackageMetaData error for @babel/preset-env@^7.12.11 Unexpected end of JSON input while parsing near '...als":"^7.8.3","@babel'
46 http fetch GET 304 https://registry.npmjs.org/coffeescript 44ms (from cache)
47 silly pacote range manifest for coffeescript@^2 fetched in 46ms
48 silly resolveWithNewModule coffeescript@2.5.1 checking installable status
49 timing stage:rollbackFailedOptional Completed in 1ms
50 timing stage:runTopLevelLifecycles Completed in 1819ms
51 silly saveTree apm-install-dir-2021118-82625-qc75bu.gniqr
51 silly saveTree `-- script@3.29.3
51 silly saveTree   +-- @babel/cli@7.12.17
51 silly saveTree   +-- @babel/core@7.12.17
51 silly saveTree   +-- @babel/preset-react@7.12.13
51 silly saveTree   +-- ansi-to-html@0.6.14
51 silly saveTree   +-- atom-message-panel@1.3.1
51 silly saveTree   +-- atom-space-pen-views-plus@3.0.4
51 silly saveTree   +-- coffeescript@2.5.1
51 silly saveTree   +-- strip-ansi@6.0.0
51 silly saveTree   +-- underscore@1.12.0
51 silly saveTree   `-- uuid@8.3.2
52 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...als":"^7.8.3","@babel'
52 verbose stack     at JSON.parse (<anonymous>)
52 verbose stack     at parseJson (/private/var/folders/rp/24bnh2750wl6z_c3lr81gszh0000gn/T/AppTranslocation/BBD2C53F-A7A3-4BB8-AE91-E1BFF9A9BBB6/d/Atom 2.app/Contents/Resources/app/apm/node_modules/npm/node_modules/json-parse-better-errors/index.js:7:17)
52 verbose stack     at /private/var/folders/rp/24bnh2750wl6z_c3lr81gszh0000gn/T/AppTranslocation/BBD2C53F-A7A3-4BB8-AE91-E1BFF9A9BBB6/d/Atom 2.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-fetch-npm/src/body.js:96:50
52 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:89:5)
53 verbose cwd /private/var/folders/rp/24bnh2750wl6z_c3lr81gszh0000gn/T/apm-install-dir-2021118-82625-qc75bu.gniqr
54 verbose Darwin 20.3.0
55 verbose argv "/private/var/folders/rp/24bnh2750wl6z_c3lr81gszh0000gn/T/AppTranslocation/BBD2C53F-A7A3-4BB8-AE91-E1BFF9A9BBB6/d/Atom 2.app/Contents/Resources/app/apm/bin/node" "/private/var/folders/rp/24bnh2750wl6z_c3lr81gszh0000gn/T/AppTranslocation/BBD2C53F-A7A3-4BB8-AE91-E1BFF9A9BBB6/d/Atom 2.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/boseongyun/.atom/.apm/.apmrc" "--userconfig" "/Users/boseongyun/.atom/.apmrc" "install" "https://www.atom.io/api/packages/script/versions/3.29.3/tarball" "--target=6.1.12" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
56 verbose node v12.4.0
57 verbose npm  v6.14.8
58 error Unexpected end of JSON input while parsing near '...als":"^7.8.3","@babel'
59 verbose exit [ 1, true ]

Here are all the logs!

**Comment by aminya** [comment]
Please re-download. This is a connection issue
