### ISSUE TITLE
Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?inva...

### ISSUE THREAD

**Issue by maydyk** [atom-community/ide-python#284]
[Enter steps to reproduce:]

1. Open python script
2. Run command from menu: Debugger|Show Debugger Pane

**Atom**: 1.54.0 x64
**Electron**: 6.1.12
**OS**: Unknown Windows version
**Thrown From**: [ide-python](https://github.com/lgeiger/ide-python) package 1.7.3

### Stack Trace

Uncaught Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130

**Comment by aminya** [comment]
This is a connection issue. Please redownload

```
apm uninstall ide-python
apm install ide-python
```

**Comment by momcilo78** [comment]
@aminya  redownload did not work for me.
