### ISSUE TITLE
go-to-definition within python modules

### ISSUE THREAD

**Issue by chakibBH** [atom-community/ide-python#286]
Hi, 
I was wondering if there is any way to go directly to the definition on an imported objects. 
As the current behaviour seems to be little odd:
- importing a class at the beginning of my python module,
- if I look after the definition (ctrl+click) in the 500th line of my awfully too long module, 
it's going to scroll up to the beginning of my module to show the import line where I need to reclick to open the expected module. 
Doing so, i'm loosing the line where I was previously.
I was wondering if there is a more straight forward to do this ? 

(I'm not sure if this can be solved using the hyperclick package, sorry if it's not the case)

**Comment by chakibBH** [comment]
Yup, my bad 
I was looking in the wrong settings (in atom-ide-hyperclick)
Having "Jedi Definition" enabled, I just forget to tick the "Follow Imports" settings
Thanks and sorry for inconvenience

**Comment by aminya** [comment]
@UziTech Can't this become a command in Hyperclick? Having deep hyperclicks (chaining) is independent of the client. I think we can have a command that changes them.

**Comment by UziTech** [comment]
@aminya if you want to work on that go ahead, but I would rather allow the package to decide what to do when text is clicked on.

**Comment by aminya** [comment]
What I am suggesting is an extra command. Like holding Shift to chain hyperclicks. Not replacing the original behavior.

**Comment by UziTech** [comment]
We could add extra commands pretty easily with different key combos, but I don't think the idea of "chaining" hyperclicks would work since it is completely up to the packages what happens when the text is clicked. They don't always just move the cursor to a different text.
