### ISSUE TITLE
Too much jedi process

### ISSUE THREAD

**Issue by gabriel-tessier** [atom-community/ide-python#290]
Hi,

After upgrading a couple of week earlier I notice that my computer became really slow... deactivating all the packages on atom I figure out that the ide-python was the root of the problem.

Checking the process list [ps-aux] I have a bunch of this call:

`gab       114869  0.4  0.1  35120 19504 ?        S    15:45   0:00 /usr/bin/python3 /home/gab/.local/lib/python3.8/site-packages/jedi/inference/compiled/subprocess/__main__.py /home/gab/.local/lib/python3.8/site-packages 3.8.5`

I need to kill all this process and start again each 2 hours or when my computer start to be slow... which is a pain on long term.

I don't know if somebody have a similar problem but any help is welcome.

More details about my system:
- Ubuntu 20.04
- Atom 1.54
- ide-python 1.7.3

**Comment by aminya** [comment]
Could you try the latest version?

**Comment by gabriel-tessier** [comment]
I upgraded to latest version and I reactived the package, let me run it a couple of hours then I'll report again here.

Thanks a lot for the fast release!

**Comment by gabriel-tessier** [comment]
@aminya 
Look fine with this upgrade thanks a lot for the release.
No more problem I close the issue.  m(__)m

**Comment by aminya** [comment]
Thanks for the report!
