### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by VincentBonnivard** [atom-community/ide-python#296]
Hello,
I'm trying to install ide-python on my fresh Atom installation (v1.55.0 on Ubuntu 16.04).

I've installed everything that was needed: 
python -m pip install 'python-language-server[all]'
apm install atom-ide-base

But then, when I run "apm install ide-python" (either in command line or from the Atom UI), I get the following error:

```
> zadeh@2.0.2 install /tmp/apm-install-dir-2021218-26874-p9dzyl.35sj/node_modules/ide-python/node_modules/zadeh
> node-gyp-build

make : on entre dans le répertoire « /tmp/apm-install-dir-2021218-26874-p9dzyl.35sj/node_modules/ide-python/node_modules/zadeh/build »
  CXX(target) Release/obj.target/zadeh/src/binding/node.o
zadeh.target.mk:142 : la recette pour la cible « Release/obj.target/zadeh/src/binding/node.o » a échouée
make : on quitte le répertoire « /tmp/apm-install-dir-2021218-26874-p9dzyl.35sj/node_modules/ide-python/node_modules/zadeh/build »

npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
In file included from ../src/binding/../zadeh.h:5:0,
                 from ../src/binding/node.h:6,
                 from ../src/binding/node.cc:3:
../src/binding/.././common.h:11:20: fatal error: optional: Aucun fichier ou dossier de ce type
 #include <optional>
                    ^
compilation terminated.
make: *** [Release/obj.target/zadeh/src/binding/node.o] Erreur 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-137-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-2021218-26874-p9dzyl.35sj/node_modules/ide-python/node_modules/zadeh
gyp ERR! node -v v12.4.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-2021218-26874-p9dzyl.35sj/package.json'
npm WARN react-dom@17.0.1 requires a peer of react@17.0.1 but none is installed. You must install peer dependencies yourself.
npm WARN react-virtualized@9.20.1 requires a peer of react-dom@^15.3.0 || ^16.0.0-alpha but none is installed. You must install peer dependencies yourself.
npm WARN apm-install-dir-2021218-26874-p9dzyl.35sj No description
npm WARN apm-install-dir-2021218-26874-p9dzyl.35sj No repository field.
npm WARN apm-install-dir-2021218-26874-p9dzyl.35sj No README data
npm WARN apm-install-dir-2021218-26874-p9dzyl.35sj No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zadeh@2.0.2 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zadeh@2.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vbonnivard/.atom/.apm/_logs/2021-03-18T17_07_08_961Z-debug.log
```

I have no idea where this comes from! Any clue from someone?
Thanks!
Vincent

**Comment by aminya** [comment]
Are you using Atom Snap?

**Comment by DevMehta** [comment]
> Hello,
> I'm trying to install ide-python on my fresh Atom installation (v1.55.0 on Ubuntu 16.04).
> 
> I've installed everything that was needed:
> python -m pip install 'python-language-server[all]'
> apm install atom-ide-base
> 
> But then, when I run "apm install ide-python" (either in command line or from the Atom UI), I get the following error:
> 
> ```
> > zadeh@2.0.2 install /tmp/apm-install-dir-2021218-26874-p9dzyl.35sj/node_modules/ide-python/node_modules/zadeh
> > node-gyp-build
> 
> make : on entre dans le répertoire « /tmp/apm-install-dir-2021218-26874-p9dzyl.35sj/node_modules/ide-python/node_modules/zadeh/build »
>   CXX(target) Release/obj.target/zadeh/src/binding/node.o
> zadeh.target.mk:142 : la recette pour la cible « Release/obj.target/zadeh/src/binding/node.o » a échouée
> make : on quitte le répertoire « /tmp/apm-install-dir-2021218-26874-p9dzyl.35sj/node_modules/ide-python/node_modules/zadeh/build »
> 
> npm WARN deprecated coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript" (no hyphen)
> npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
> In file included from ../src/binding/../zadeh.h:5:0,
>                  from ../src/binding/node.h:6,
>                  from ../src/binding/node.cc:3:
> ../src/binding/.././common.h:11:20: fatal error: optional: Aucun fichier ou dossier de ce type
>  #include <optional>
>                     ^
> compilation terminated.
> make: *** [Release/obj.target/zadeh/src/binding/node.o] Erreur 1
> gyp ERR! build error 
> gyp ERR! stack Error: `make` failed with exit code: 2
> gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
> gyp ERR! stack     at ChildProcess.emit (events.js:200:13)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
> gyp ERR! System Linux 4.15.0-137-generic
> gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /tmp/apm-install-dir-2021218-26874-p9dzyl.35sj/node_modules/ide-python/node_modules/zadeh
> gyp ERR! node -v v12.4.0
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-2021218-26874-p9dzyl.35sj/package.json'
> npm WARN react-dom@17.0.1 requires a peer of react@17.0.1 but none is installed. You must install peer dependencies yourself.
> npm WARN react-virtualized@9.20.1 requires a peer of react-dom@^15.3.0 || ^16.0.0-alpha but none is installed. You must install peer dependencies yourself.
> npm WARN apm-install-dir-2021218-26874-p9dzyl.35sj No description
> npm WARN apm-install-dir-2021218-26874-p9dzyl.35sj No repository field.
> npm WARN apm-install-dir-2021218-26874-p9dzyl.35sj No README data
> npm WARN apm-install-dir-2021218-26874-p9dzyl.35sj No license field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! zadeh@2.0.2 install: `node-gyp-build`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the zadeh@2.0.2 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/vbonnivard/.atom/.apm/_logs/2021-03-18T17_07_08_961Z-debug.log
> ```
> 
> I have no idea where this comes from! Any clue from someone?
> Thanks!
> Vincent

Same Problem

**Comment by aminya** [comment]
Could you give me the log? @DevMehta 

Try re-downloading.

```
apm uninstall ide-python
```
Clear your cache then

```
apm install ide-python
```

**Comment by DevMehta** [comment]
> Could you give me the log? @DevMehta
> 
> Try re-downloading.
> 
> ```
> apm uninstall ide-python
> ```
> 
> Clear your cache then
> 
> ```
> apm install ide-python
> ```


Log File:

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Users\\pc\\AppData\\Local\\atom\\app-1.56.0\\resources\\app\\apm\\bin\\node.exe',
1 verbose cli   'C:\\Users\\pc\\AppData\\Local\\atom\\app-1.56.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   '--globalconfig',
1 verbose cli   'C:\\Users\\pc\\.atom\\.apm\\.apmrc',
1 verbose cli   '--userconfig',
1 verbose cli   'C:\\Users\\pc\\.atom\\.apmrc',
1 verbose cli   'install',
1 verbose cli   'https://www.atom.io/api/packages/ide-python/versions/1.8.0/tarball',
1 verbose cli   '--target=9.4.4',
1 verbose cli   '--disturl=https://atom.io/download/electron',
1 verbose cli   '--arch=x64',
1 verbose cli   '--global-style'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.4.0
4 verbose npm-session 1adf892254597dff
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://codeload.github.com/atom-community/ide-python/legacy.tar.gz/refs/tags/v1.8.0 2819ms (from cache)
8 silly fetchPackageMetaData error for https://www.atom.io/api/packages/ide-python/versions/1.8.0/tarball zlib: unexpected end of file
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 3021ms
11 verbose stack ZlibError: zlib: unexpected end of file
11 verbose stack     at Unzip.write (C:\Users\pc\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:147:22)
11 verbose stack     at Unzip.flush (C:\Users\pc\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:98:10)
11 verbose stack     at Unzip.end (C:\Users\pc\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\minizlib\index.js:104:10)
11 verbose stack     at Object.end (C:\Users\pc\AppData\Local\atom\app-1.56.0\resources\app\apm\node_modules\npm\node_modules\tar\lib\parse.js:421:21)
11 verbose stack     at PassThrough.onend (_stream_readable.js:675:10)
11 verbose stack     at Object.onceWrapper (events.js:288:20)
11 verbose stack     at PassThrough.emit (events.js:205:15)
11 verbose stack     at endReadableNT (_stream_readable.js:1154:12)
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:84:9)
12 verbose cwd C:\Users\pc\AppData\Local\Temp\apm-install-dir-2021410-9720-jp1k5l.g2trp
13 verbose Windows_NT 10.0.19042
14 verbose argv "C:\\Users\\pc\\AppData\\Local\\atom\\app-1.56.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\pc\\AppData\\Local\\atom\\app-1.56.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\pc\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\pc\\.atom\\.apmrc" "install" "https://www.atom.io/api/packages/ide-python/versions/1.8.0/tarball" "--target=9.4.4" "--disturl=https://atom.io/download/electron" "--arch=x64" "--global-style"
15 verbose node v12.4.0
16 verbose npm  v6.14.8
17 error code Z_BUF_ERROR
18 error errno -5
19 error zlib: unexpected end of file
20 verbose exit [ -5, true ]


And ide-python was never installed in the first place so can not try re-installing, but language server and ide-base were installed
[
![Capture](https://user-images.githubusercontent.com/70589563/117648149-7f685500-b1ab-11eb-9fc9-9a83b7180f1f.PNG)
](url)

**Comment by aminya** [comment]
Install the latest version
