### ISSUE TITLE
Cannot disable automatic reformatting

### ISSUE THREAD

**Issue by M-Demay** [atom-community/ide-python#362]
Hi !

**Issue and steps to reproduce**
 Since the last version, the plugin reformats my code each time I hit ctrl-s, even if the file had no change to save. I tried to deactivate all the options (linters etc.) and it still does this automatic reformatting.

**Current solution**
I downgraded to 1.9.3 and this behaviour stops, even with all linters activated. Did you implement this on purpose ? Unless I'm mistaken, I don't find it in the release notes of v1.9.4. If it is on purpose, or if you plan to make it the default behaviour, personally I would prefer to have the choice of whether it formats my code or not :)

**OS**
Ubuntu 20.04.2 LTS

**Non-built-in packages**
├── atom-ide-base@3.4.0
├── atom-ide-code-format@1.0.2
├── atom-ide-datatip@0.25.0
├── atom-ide-definitions@0.4.1
├── atom-ide-hyperclick@1.0.11
├── atom-ide-markdown-service@2.1.0
├── atom-ide-outline@3.1.0
├── atom-ide-signature-help@0.16.0
├── autocomplete-python@1.17.0
├── busy-signal@2.0.1
├── docblock-python@0.19.1
├── ide-python@1.9.4
├── intentions@2.1.1
├── language-latex@1.2.0
├── latex@0.50.2
├── linter@3.4.0
├── linter-ui-default@3.4.1
└── vim-mode-plus@1.36.6

**Comment by aminya** [comment]
Disable Format on save from the settings of atom-ide-code-format

**Comment by M-Demay** [comment]
Yeah I actually figured this out in the end. Sorry for bothering you and for erroneously blaming this plugin. I think I updated `atom-ide-base` and `ide-python` at the same time and that caused the problem. But I thought `atom-ide-code-format` hadn't been updated. Do you know if it may have been updated at the same time as `atom-ide-base` under the hood? Or if I just wasn't careful enough? I am pretty new to Atom.

**Comment by aminya** [comment]
atom-ide-base updates should automatically install atom-ide-code-format. The packages are automatically updated by Atom itself. So, unless you have downgraded something manually, it should work with no issues.

My suggestion is to not downgrade things unless there is a severe bug that breaks your workflow.

**Comment by M-Demay** [comment]
All right, thanks a lot ! I am back to 1.9.4.
