### ISSUE TITLE
None of the config works with pylsp

### ISSUE THREAD

**Issue by matthewgdv** [atom-community/ide-python#373]
While replacing pyls with pylsp has fixed a lot of broken functionality, none of the config seems to work. No matter what you change it just sticks to the default package config.

For instance, even after disabling pycodestyle, the linter still produces pycodestyle-related errors, and any error codes you add to the ignore list are still shown.

Likewise, even after disabling all Jedi-related functionality, Jedi is still fully active.

If this could be fixed we'd be in a really good spot, seeing as how pylsp seems to be actively maintained :)

**Comment by aminya** [comment]
This might be related to 
https://github.com/atom-community/ide-python/blob/master/lib/main.js-L45

**Comment by aminya** [comment]
PRs are welcome.
