### ISSUE TITLE
Can't disable code formatting on save

### ISSUE THREAD

**Issue by mzannoni** [atom-community/ide-python#375]
autopep8 and Yapf are both disabled. Atom has been restarted.

However, every time I press Ctrl+S, the entire file is changed (due to reformatting of white spaces, mostly).

This happens since last update of the ide-python package.

I think this is a bug.
At the moment, I had to disable ide-python.

Atom: 1.58
ide-python: 1.9.4
Ubuntu 20.04.2 LTS x86_64

**Comment by mzannoni** [comment]
I don't know if it's related.
Another thing that is happening since last update is that at start, Atom warns that the linter and the diagnistics are conflicting and one of the 2 should be disabled.

**Comment by mzannoni** [comment]
Additional note: downgrading ide-python to v 1.9.3 solves this issue (but not the one with the linter and diagnostics, so I suspect this latter is not necessarily related).

**Comment by aminya** [comment]
You should try disabling the atom-ide-code-format package.

**Comment by s-m-e** [comment]
> Another thing that is happening since last update is that at start, Atom warns that the linter and the diagnistics are conflicting and one of the 2 should be disabled.

I can confirm this behavior. Only workaround I could find (so far): Starting all over with a fresh Atom profile folder.

**Comment by aminya** [comment]
Inside atom-ide-code-format settings remove the option for "automatic code formatting on save"

**Comment by mzannoni** [comment]
> Inside atom-ide-code-format settings remove the option for "automatic code formatting on save"

Yes, I confirm this works, but it disables entirely the code formatting features (also the ones given by "whitespace" plugin for instance.
The only issue I see now is with ide-python (which was not there in previous versions). It seems I can't disable code formatting features of ide-python (some are a bit annoying, like when it re-arranges entire portions of code, e.g. swapping lines to put all the imports at the beginning [yes, I know it's is best practice... but I'd like to be free to write badly formatted code if I need/want]).

**Comment by mzannoni** [comment]
Ok, I've seen just now that a new version of ide-python was available.
It seems taht solves the issue: disabling autopep8 effectively prevents code formatting on save (enabling it works properly as well, e.g. "import" lines are shoved all the way to the top of a file).

I guess this could be considered solved?
(but yeah, I still have the notice at Atom startup about linter vs. diagnostics... not sure what to do with that)

**Comment by aminya** [comment]
Thanks!
