### ISSUE TITLE
Package error

### ISSUE THREAD

**Issue by amanjitsk** [atom-community/ide-python#40]
Thanks again for the great work!
This package however stopped working again, and none of the features work! 
For example, in the `Outline view` it says `No outline available. There is likely an error with the language package.` The autocomplete and rest of the features also don't work.

**Comment by psych0der** [comment]
Same here, after a short time, all features stop working.

**Comment by lgeiger** [comment]
Which version of `python-language-server` are you using?

**Comment by psych0der** [comment]
python-language-server==0.11.1

**Comment by lgeiger** [comment]
Thanks for the fast answer. Could you try `python-language-server v0.10.0`?
The new rope completions in `pyls` may have introduced some regressions.

**Comment by psych0der** [comment]
Sure, let me try it and get back if the issue still persists. BTW, thanks for this awesome package.

**Comment by psych0der** [comment]
I reverted to v0.10.0 and still, the package stops working after some time. For the context, I am using python-tools and autocomplete-python along with this package. Do you feel that these packages are not compatible with ide-python?

**Comment by amanjitsk** [comment]
Yup same setup as @psych0der and same issue persists and I have `pyls` version `python-language-server (0.11.1)` (from `pip3 list`). Also @psych0der I have to disable this packages `jedi completion` in order to get my autocomplete properly formatted (due to `autocomplete-python` also providing autocomplete).. but it doesn't seem to matter anymore, `ide-python` just stopped working now.

**Comment by detourbr** [comment]
Same issue running atom and ide-python under Kali Linux. My configuration is the following :
```
jedi (0.11.0)
mccabe (0.6.1)
pycodestyle (2.3.1)
pydocstyle (2.1.1)
python-language-server (0.11.1)
yapf (0.18.0)
```
For autocompletion : I've got issues using autocomplete-python but all is fine with python-jedi

**Comment by patrickmch** [comment]
This package is awesome. Thanks for making it. I do have the same issue though.
After 10 minutes running ide-python on MacOS Sierra, Python begins taking a ton of CPU (~140%) and the package stops working. Disabling ide-python stops the cpu hogging.

**Comment by jake-westfall** [comment]
Same issue. No features work at all, with either `python-language-server==0.10.0` or `python-language-server==0.12.1`.

**Comment by lgeiger** [comment]
There've been a lot of performance improvements in the latest release of the language server.

Could you check if this is still reproducible with `python-language-server==0.17.0` and `ide-python==0.9.0`?

To upgrade the server run:
```shell
pip install 'python-language-server[all]' --upgrade
```

**Comment by detourbr** [comment]
Much better !
It seems to be working ! The only bug I found was triggered for modules imported the following syntax : `from .module import *`
Instead of `from module import`
Useful when you want to force an import of a module located in the local folder
