### ISSUE TITLE
Unable to start the Python language server

### ISSUE THREAD

**Issue by Chris-Rasburn** [atom-community/ide-python#469]
I'm getting the following error message:

>Unable to start the Python language server.
>
>Make sure to install pylsp 0.19 or newer by running:
>
>python -m pip install 'python-lsp-server[all]'
>python -m pip install git+https://github.com/tomv564/pyls-mypy.git

I'm new to all this, so probably did something wrong.  I assumed that as I'm running python3 I should replace 'python' above with 'python3'.  The above installations worked correctly.

I've seen that previously there was an issue that was fixed by making python3 the default in the 'python executable' option - this doesn't help me because python3 is now the default.

I'm using:  
- WSL2,  
- Debian 1.12.1.0,  
- Atom 1.58.0.  
- Python 3.9.2  
- ide-python 1.9.7

python3 -m pyls --help       returns:

>usage: __ main __.py [-h] [--tcp] [--host HOST] [--port PORT] [--check-parent-process] [--log-config LOG_CONFIG | --log-file LOG_FILE] [-v]
>
>Python Language Server  
> .....

python -m pyls --help       returns:

>/usr/bin/python: No module named pyls

I'm sure there is a simple answer to this, but I'm baffled.  Apologies if this isn't the right place to ask this question - point me to the right place.

**Comment by Chris-Rasburn** [comment]
Sorted.

**Comment by Jul352mf** [comment]
I got the same problem. How did you solve it?

**Comment by Chris-Rasburn** [comment]
I switched from Atom :(
